CREATE TABLE itest1 (a int generated by default as identity, b text);
CREATE TABLE itest2 (a bigint generated always as identity, b text);
CREATE TABLE itest3 (a smallint generated by default as identity (start with 7 increment by 5), b text);
ALTER TABLE itest3 ALTER COLUMN a ADD GENERATED ALWAYS AS IDENTITY;  -- error
ERROR:  column "a" of relation "itest3" is already an identity column
SELECT table_name, column_name, column_default, is_nullable, is_identity, identity_generation, identity_start, identity_increment, identity_maximum, identity_minimum, identity_cycle FROM information_schema.columns WHERE table_name LIKE 'itest_' ORDER BY 1, 2;
 table_name | column_name | column_default | is_nullable | is_identity | identity_generation | identity_start | identity_increment |  identity_maximum   | identity_minimum | identity_cycle 
------------+-------------+----------------+-------------+-------------+---------------------+----------------+--------------------+---------------------+------------------+----------------
 itest1     | a           |                | NO          | YES         | BY DEFAULT          | 1              | 1                  | 2147483647          | 1                | NO
 itest1     | b           |                | YES         | NO          |                     |                |                    |                     |                  | NO
 itest2     | a           |                | NO          | YES         | ALWAYS              | 1              | 1                  | 9223372036854775807 | 1                | NO
 itest2     | b           |                | YES         | NO          |                     |                |                    |                     |                  | NO
 itest3     | a           |                | NO          | YES         | BY DEFAULT          | 7              | 5                  | 32767               | 1                | NO
 itest3     | b           |                | YES         | NO          |                     |                |                    |                     |                  | NO
(6 rows)
-- internal sequences should not be shown here
SELECT sequence_name FROM information_schema.sequences WHERE sequence_name LIKE 'itest%';
 sequence_name 
---------------
(0 rows)

ALTER TABLE itest3 ALTER COLUMN a ADD GENERATED ALWAYS AS IDENTITY;  -- error
invalid syntax: statement ignored: at or near "generated": syntax error: unimplemented: this syntax
SELECT table_name, column_name, column_default, is_nullable, is_identity, identity_generation, identity_start, identity_increment, identity_maximum, identity_minimum, identity_cycle FROM information_schema.columns WHERE table_name LIKE 'itest_' ORDER BY 1, 2;
  table_name | column_name |              column_default              | is_nullable | is_identity | identity_generation | identity_start | identity_increment | identity_maximum | identity_minimum | identity_cycle
-------------+-------------+------------------------------------------+-------------+-------------+---------------------+----------------+--------------------+------------------+------------------+-----------------
  itest1     | a           | nextval('public.itest1_a_seq'::REGCLASS) | NO          | YES         | BY DEFAULT          | NULL           | NULL               | NULL             | NULL             | NULL
  itest1     | b           | NULL                                     | YES         | NO          |                     | NULL           | NULL               | NULL             | NULL             | NULL
  itest1     | rowid       | unique_rowid()                           | NO          | NO          |                     | NULL           | NULL               | NULL             | NULL             | NULL
  itest2     | a           | nextval('public.itest2_a_seq'::REGCLASS) | NO          | YES         | ALWAYS              | NULL           | NULL               | NULL             | NULL             | NULL
  itest2     | b           | NULL                                     | YES         | NO          |                     | NULL           | NULL               | NULL             | NULL             | NULL
  itest2     | rowid       | unique_rowid()                           | NO          | NO          |                     | NULL           | NULL               | NULL             | NULL             | NULL
  itest3     | a           | nextval('public.itest3_a_seq'::REGCLASS) | NO          | YES         | BY DEFAULT          | NULL           | NULL               | NULL             | NULL             | NULL
  itest3     | b           | NULL                                     | YES         | NO          |                     | NULL           | NULL               | NULL             | NULL             | NULL
  itest3     | rowid       | unique_rowid()                           | NO          | NO          |                     | NULL           | NULL               | NULL             | NULL             | NULL
(9 rows)

SELECT sequence_name FROM information_schema.sequences WHERE sequence_name LIKE 'itest%';
 sequence_name
-----------------
  itest1_a_seq
  itest2_a_seq
  itest3_a_seq
(3 rows)

-- tests for tidscans
CREATE TABLE tidscan(id integer);
-- only insert a few rows, we don't want to spill onto a second table page
INSERT INTO tidscan VALUES (1), (2), (3);
-- show ctids
SELECT ctid, * FROM tidscan;
 ctid  | id 
-------+----
 (0,1) |  1
 (0,2) |  2
 (0,3) |  3
(3 rows)

hash-threshold 8
CREATE TABLE tab0(pk INTEGER PRIMARY KEY, col0 INTEGER, col1 FLOAT, col2 TEXT, col3 INTEGER, col4 FLOAT, col5 TEXT)
INSERT INTO tab0 VALUES(0,393,418.53,'qmdjn',400,388.84,'rrzmu')
INSERT INTO tab0 VALUES(1,396,421.19,'wusyk',401,391.9,'puulf')
INSERT INTO tab0 VALUES(2,397,422.72,'kyyoq',402,392.80,'fvxdj')
INSERT INTO tab0 VALUES(3,400,424.67,'locym',403,393.37,'hbnhk')
INSERT INTO tab0 VALUES(4,401,425.97,'ensaj',404,394.91,'kwthq')
INSERT INTO tab0 VALUES(5,402,427.54,'toqtb',406,395.78,'iiost')
INSERT INTO tab0 VALUES(6,403,428.88,'mzhmu',407,397.31,'atzxa')
INSERT INTO tab0 VALUES(7,404,429.77,'bdqui',408,398.36,'umfsi')
INSERT INTO tab0 VALUES(8,406,430.82,'mflyd',409,399.96,'lkwdh')
INSERT INTO tab0 VALUES(9,410,431.14,'jqhro',412,403.94,'koxsj')
CREATE TABLE tab1(pk INTEGER PRIMARY KEY, col0 INTEGER, col1 FLOAT, col2 TEXT, col3 INTEGER, col4 FLOAT, col5 TEXT)
CREATE INDEX idx_tab1_0 on tab1 (col0)
CREATE INDEX idx_tab1_1 on tab1 (col1)
CREATE INDEX idx_tab1_3 on tab1 (col3)
CREATE INDEX idx_tab1_4 on tab1 (col4)
INSERT INTO tab1 SELECT * FROM tab0
CREATE TABLE tab2(pk INTEGER PRIMARY KEY, col0 INTEGER, col1 FLOAT, col2 TEXT, col3 INTEGER, col4 FLOAT, col5 TEXT)
CREATE UNIQUE INDEX idx_tab2_0 ON tab2 (col4 DESC,col0 DESC)
CREATE INDEX idx_tab2_2 ON tab2 (col1)
CREATE UNIQUE INDEX idx_tab2_3 ON tab2 (col0 DESC,col4)
CREATE UNIQUE INDEX idx_tab2_5 ON tab2 (col3 DESC)
INSERT INTO tab2 SELECT * FROM tab0
CREATE TABLE tab3(pk INTEGER PRIMARY KEY, col0 INTEGER, col1 FLOAT, col2 TEXT, col3 INTEGER, col4 FLOAT, col5 TEXT)
CREATE INDEX idx_tab3_0 ON tab3 (col4)
INSERT INTO tab3 SELECT * FROM tab0
CREATE TABLE tab4(pk INTEGER PRIMARY KEY, col0 INTEGER, col1 FLOAT, col2 TEXT, col3 INTEGER, col4 FLOAT, col5 TEXT)
CREATE INDEX idx_tab4_0 ON tab4 (col3 DESC)
CREATE UNIQUE INDEX idx_tab4_1 ON tab4 (col4 DESC)
CREATE INDEX idx_tab4_4 ON tab4 (col0)
INSERT INTO tab4 SELECT * FROM tab0
SELECT pk FROM tab0 WHERE (col3 > 10 AND col0 > 56) ORDER BY 1 DESC
SELECT pk FROM tab1 WHERE (col3 > 10 AND col0 > 56) ORDER BY 1 DESC
SELECT pk FROM tab2 WHERE (col3 > 10 AND col0 > 56) ORDER BY 1 DESC
SELECT pk FROM tab3 WHERE (col3 > 10 AND col0 > 56) ORDER BY 1 DESC
SELECT pk FROM tab4 WHERE (col3 > 10 AND col0 > 56) ORDER BY 1 DESC
SELECT pk FROM tab0 WHERE (col3 > 10 AND col0 > 56) ORDER BY 1
SELECT pk FROM tab1 WHERE (col3 > 10 AND col0 > 56) ORDER BY 1
SELECT pk FROM tab2 WHERE (col3 > 10 AND col0 > 56) ORDER BY 1
SELECT pk FROM tab3 WHERE (col3 > 10 AND col0 > 56) ORDER BY 1
SELECT pk FROM tab4 WHERE (col3 > 10 AND col0 > 56) ORDER BY 1
SELECT pk, col0 FROM tab0 WHERE (col3 > 10 AND col0 > 56) ORDER BY 1 DESC
----
20 values hashing to 7dc4dd9c0c522fd8ec56cbc33525a146
SELECT pk, col0 FROM tab1 WHERE (col3 > 10 AND col0 > 56) ORDER BY 1 DESC
----
20 values hashing to 7dc4dd9c0c522fd8ec56cbc33525a146
SELECT pk, col0 FROM tab2 WHERE (col3 > 10 AND col0 > 56) ORDER BY 1 DESC
----
20 values hashing to 7dc4dd9c0c522fd8ec56cbc33525a146
SELECT pk, col0 FROM tab3 WHERE (col3 > 10 AND col0 > 56) ORDER BY 1 DESC
----
20 values hashing to 7dc4dd9c0c522fd8ec56cbc33525a146
SELECT pk, col0 FROM tab4 WHERE (col3 > 10 AND col0 > 56) ORDER BY 1 DESC
----
20 values hashing to 7dc4dd9c0c522fd8ec56cbc33525a146
SELECT pk, col0 FROM tab0 WHERE (col3 > 10 AND col0 > 56) ORDER BY 2 DESC
----
20 values hashing to 7dc4dd9c0c522fd8ec56cbc33525a146
SELECT pk, col0 FROM tab1 WHERE (col3 > 10 AND col0 > 56) ORDER BY 2 DESC
----
20 values hashing to 7dc4dd9c0c522fd8ec56cbc33525a146
SELECT pk, col0 FROM tab2 WHERE (col3 > 10 AND col0 > 56) ORDER BY 2 DESC
----
20 values hashing to 7dc4dd9c0c522fd8ec56cbc33525a146
SELECT pk, col0 FROM tab3 WHERE (col3 > 10 AND col0 > 56) ORDER BY 2 DESC
----
20 values hashing to 7dc4dd9c0c522fd8ec56cbc33525a146
SELECT pk, col0 FROM tab4 WHERE (col3 > 10 AND col0 > 56) ORDER BY 2 DESC
----
20 values hashing to 7dc4dd9c0c522fd8ec56cbc33525a146
SELECT pk, col0 FROM tab0 WHERE (col3 > 10 AND col0 > 56) ORDER BY 1
----
20 values hashing to 71417f66dacbe609cdaf87bc08ead392


CALL mtr.add_suppression("Enabling keys got errno");
drop table if exists t1,t2;
SET SQL_WARNINGS=1;
SET sql_mode = 'NO_ENGINE_SUBSTITUTION';
SET @default_table_open_cache = @@table_open_cache;
CREATE TABLE t1 (
STRING_DATA char(255) default NULL,
KEY string_data (STRING_DATA)
) charset latin1 ENGINE=MyISAM;
INSERT INTO t1 VALUES ('AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA');

statement ok
create sequence seq1 INCREMENT BY 1 MINVALUE 9223372036854775800 MAXVALUE 9223372036854775807 CYCLE;

query I
SELECT nextval('seq1') from generate_series(0,20);
----
9223372036854775800
9223372036854775801
9223372036854775802
9223372036854775803
9223372036854775804
9223372036854775805
9223372036854775806
9223372036854775807
9223372036854775800
9223372036854775801
9223372036854775802
9223372036854775803
9223372036854775804
9223372036854775805
9223372036854775806
9223372036854775807
9223372036854775800
9223372036854775801
9223372036854775802
9223372036854775803
9223372036854775804